# Lean pre-commit configuration - only the essentials
repos:
  # Essential file hygiene
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict

  # Python code quality - ruff does it all (linting + formatting)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

# Simple configuration
default_stages: [pre-commit]
fail_fast: true  # Stop on first failure for faster feedback

# Exclude common directories
exclude: |
  (?x)^(
      \.venv/.*|
      __pycache__/.*|
      \.pytest_cache/.*|
      build/.*|
      dist/.*
  )$
